# Generated by Django 3.2 on 2023-06-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_rename_item2_item_list_item3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Item_list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='pass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.user'),
        ),
    ]
