# Generated by Django 3.2 on 2023-06-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20230617_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='user',
            new_name='passuser',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='email',
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.user')),
            ],
        ),
    ]
